spring.application.name=e-commerce-user-behaviors-tracker

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.topic=user-events
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true